from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
import time
import logging

class NoReceipt():
    def __init__(self):
        self.success = False
    
    #Only works for postpay
    def normal_submit_procedure(self, driver, prepay):
        submit_claim_btn = driver.find_element(By.CLASS_NAME, "sc-bjUoiL.leXMUQ")
        time.sleep(5)
        submit_claim_btn.click()
        if prepay:
            self.prepay_thingy(driver)
        no_recipt = driver.find_element(By.CLASS_NAME, "ClaimSubmission_text__cNzhv")
        time.sleep(5)
        no_recipt.click()
        continue_btn = driver.find_element(By.CLASS_NAME, "sc-bBXxYQ.hlpCAH")
        time.sleep(5)
        continue_btn.click()
        online_btn = driver.find_element(By.XPATH, "//*[@id='root']/div/div/div/div[2]/div/div[2]/div/div[2]/button[2]")
        time.sleep(5)
        online_btn.click()
        merchant_input = driver.find_element(By.NAME, "merchantWebsite")
        merchant_input.send_keys("test.com")
        date_input = driver.find_element(By.NAME, "date")
        date_input.send_keys("03/03/2023")
        total_paid = driver.find_element(By.NAME, "totalPaid")
        total_paid.send_keys("1")
        time.sleep(5)
        claim_amount = driver.find_element(By.NAME, "amountToClaim")
        claim_amount.send_keys("1")
        time.sleep(5)
        claim_submit_btn = driver.find_element(By.XPATH, "//*[@id='root']/div/div/div/div[2]/div/div[2]/div/div[3]/button[1]")
        claim_submit_btn.click()
        time.sleep(10)
    
    def submit_hsa(self, driver):
        health_btn = driver.find_element(By.XPATH,"//*[contains(text(),'Health')]")
        health_btn.click()
        time.sleep(5)
        print("dropdown")
        select_box_1 = driver.find_elements(By.ID, "ClaimSubmission_dropdownContainerStyle__1dMIR_input")
        print(len(select_box_1))
        select_box_1[0].click()
        print("Clicked select box 1")
        time.sleep(5)
        options = driver.find_elements(By.CLASS_NAME, "rw-list-option")
        options[0].click()
        print("Clicked dental thingy")
        time.sleep(5)
        select_box_2 = driver.find_elements(By.ID, "ClaimSubmission_dropdownContainerStyle__1dMIR_input")
        select_box_2[1].click()
        print("Clicked sub category thingy ")
        time.sleep(5)
        options = driver.find_elements(By.CLASS_NAME, "rw-list-option")
        options[6].click()
        time.sleep(5)
        item_amount = driver.find_element(By.NAME, "claimItems.0.amountPaid")
        item_amount.send_keys("1")
        print("Sent amount thingy ")
        time.sleep(5)
        select_box_2[2].click()
        print("Clicked person thingy ")
        time.sleep(5)
        options = driver.find_elements(By.CLASS_NAME, "rw-list-option")
        print(len(options))
        options[10].click()
        print("Clicked emp2 thingy ")
        time.sleep(5)
        chck_btn = driver.find_element(By.CLASS_NAME, "sc-cBsrDa.fIiskw")
        chck_btn.click()
        print("Clicked check btn thingy ")
        time.sleep(5)
        submit_btn = driver.find_elements(By.CLASS_NAME, "sc-bBXxYQ.hlpCAH")
        submit_btn[1].click()
        print("Submit btn clicked ")
        print("Claim Submitted Successfully!!!!")
        time.sleep(7)
    
    def submit_wsa(self, driver):
        wellness_btn = driver.find_element(By.XPATH,"//*[contains(text(),'Wellness')]")
        wellness_btn.click()
        print("waiting for dropdown")
        time.sleep(15)
        print("dropdown")
        #drop_down=driver.find_element(By.XPATH, "(//div[@class='rw-dropdown-list-input'])[1]")
        #drop_down.click()
        select_box_1 = driver.find_elements(By.ID, "ClaimSubmission_dropdownContainerStyle__1dMIR_input")
        print(len(select_box_1))
        #select_box_1 = driver.find_element(By.CSS_SELECTOR, "#ClaimSubmission_dropdownContainerStyle__1dMIR_input[data-testid = 'majorCategory-0-dropdown']")
        select_box_1[0].click()
        print("Clicked select box 1")
        time.sleep(10)
        wellness_spending = driver.find_element(By.ID, "ClaimSubmission_dropdownContainerStyle__1dMIR_listbox")
        wellness_spending.click()
        print("Clicked wellness_spending thingy ")
        time.sleep(5)
        select_box_2 = driver.find_elements(By.ID, "ClaimSubmission_dropdownContainerStyle__1dMIR_input")
        select_box_2[1].click()
        print("Clicked sub category thingy ")
        time.sleep(5)
        options = driver.find_elements(By.CLASS_NAME, "rw-list-option")
        options[1].click()
        print("Clicked fitness thingy")
        time.sleep(5)
        item_amount = driver.find_element(By.NAME, "claimItems.0.amountPaid")
        item_amount.send_keys("1")
        print("Sent amount thingy ")
        time.sleep(5)
        select_box_2[2].click()
        print("Clicked person thingy ")
        time.sleep(5)
        options = driver.find_elements(By.CLASS_NAME, "rw-list-option")
        options[5].click()
        print("Clicked emp2 thingy ")
        time.sleep(5)
        chck_btn = driver.find_element(By.CLASS_NAME, "sc-cBsrDa.fIiskw")
        chck_btn.click()
        print("Clicked check btn thingy ")
        time.sleep(5)
        submit_btn = driver.find_elements(By.CLASS_NAME, "sc-bBXxYQ.hlpCAH")
        submit_btn[1].click()
        print("Submit btn clicked ")
        print("Claim Submitted Successfully!!!!")
        time.sleep(7)
    
    def prepay_thingy(self, driver):
        out_of_pocket = driver.find_element(By.CLASS_NAME, "ui.grey.basic.button.sc-kLLXSd.atWDV")
        out_of_pocket.click()
        time.sleep(5)

    def submit_hsa_wsa(self, driver, prepay):
        self.normal_submit_procedure(driver, prepay)
        time.sleep(5)
        self.submit_wsa(driver)
     
    def submit_wsa_only(self, driver, prepay):
        self.normal_submit_procedure(driver, prepay)
        self.submit_wsa(driver)
    
    def submit_hsa_only(self, driver, prepay):
        self.normal_submit_procedure(driver, prepay)
        self.submit_hsa(driver)
